version: "3"
services:
  openvpn_holder_container:
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - '9050:1080'
    volumes:
      - <path-to-your-openvpn-config>:/config/vpn.ovpn
      - <path-to-your-credentials>:/config/credentials.txt
    dns: 208.67.222.222
    cap_drop:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    privileged: true