version: "3"
services:
  openvpn_holder_container:
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - '127.0.0.1:9050:1080'
    volumes:
      - "./config/Vypr_OpenVPN_20200320/GF_OpenVPN_20200320/OpenVPN256/Iceland.ovpn:/config/vpn.ovpn"
      - ./config/vyprvpn_credentials.txt:/config/credentials.txt
    restart: unless-stopped
    dns: 208.67.222.222
    cap_drop:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    privileged: true